
template:
  - trigger:
      - platform: event
        event_type: "state_changed"
        event_data:
          entity_id: sensor.electricity_charge_balance_户号
    sensor:
      - name: electricity_charge_balance_entity_户号
        unique_id: electricity_charge_balance_entity_户号
        state: "{{ states('sensor.electricity_charge_balance_户号') }}"
        state_class: total
        unit_of_measurement: "CNY"
        device_class: monetary

  - trigger:
      - platform: event
        event_type: "state_changed"
        event_data:
          entity_id: sensor.last_electricity_usage_户号
    sensor:
      - name: last_electricity_usage_entity_户号
        unique_id: last_electricity_usage_entity_户号
        state: "{{ states('sensor.last_electricity_usage_户号') }}"
        state_class: measurement # total_increasing
        unit_of_measurement: "kWh" # string (optional, default: None)
        device_class: energy

  - trigger:
      - platform: event
        event_type: "state_changed"
        event_data:
          entity_id: sensor.month_electricity_usage_户号
    sensor:
      - name: month_electricity_usage_entity_户号
        unique_id: month_electricity_usage_entity_户号
        state: "{{ states('sensor.month_electricity_usage_户号') }}"
        state_class: measurement
        unit_of_measurement: "kWh"
        device_class: energy

  - trigger:
      - platform: event
        event_type: "state_changed"
        event_data:
          entity_id: sensor.month_electricity_charge_户号
    sensor:
      - name: month_electricity_charge_entity_户号
        unique_id: month_electricity_charge_entity_户号
        state: "{{ states('sensor.month_electricity_charge_户号') }}"
        state_class: measurement
        unit_of_measurement: "CNY"
        device_class: monetary

  - trigger:
      - platform: event
        event_type: "state_changed"
        event_data:
          entity_id: sensor.yearly_electricity_usage_户号
    sensor:
      - name: yearly_electricity_usage_entity_户号
        unique_id: yearly_electricity_usage_entity_户号
        state: "{{ states('sensor.yearly_electricity_usage_户号') }}"
        state_class: total_increasing
        unit_of_measurement: "kWh"
        device_class: energy

  - trigger:
      - platform: event
        event_type: "state_changed"
        event_data:
          entity_id: sensor.yearly_electricity_charge_户号
    sensor:
      - name: yearly_electricity_charge_entity_户号
        unique_id: yearly_electricity_charge_entity_户号
        state: "{{ states('sensor.yearly_electricity_charge_户号') }}"
        state_class: total_increasing
        unit_of_measurement: "CNY"
        device_class: monetary
