build_from:
  aarch64: registry.cn-hangzhou.aliyuncs.com/arcw/sgcc_electricity:latest
  amd64: registry.cn-hangzhou.aliyuncs.com/arcw/sgcc_electricity:latest
labels:
  org.opencontainers.image.title: "SGCC Electricity Add-on"
  org.opencontainers.image.description: "State Grid Electric Data"
  org.opencontainers.image.source: "https://github.com/ARC-MX/sgcc_electricity_new"
