name: "SGCC Electricity"
version: "v0.1.0"
slug: "sgcc_electricity"
description: "获取国网电费数据的插件"
url: "https://github.com/ARC-MX/sgcc_electricity_new"
arch:
  - aarch64
  - amd64
host_network: true
startup: application
boot: auto
init: false
# image: "registry.cn-hangzhou.aliyuncs.com/arcw/sgcc_electricity-{arch}"
map:
  - config:rw
options:
  phone: ""
  password: ""  
  ignore_user_id: "xxxx,xxxx"
  enable_database_storage: false
  db_name: "homeassistant.db"
  hass_url: "http://homeassistant.local:8123/"
  hass_token: ""
  job_start_time: "07:00"
  retry_wait_time_offset_unit: 15
  data_retention_days: 7
  recharge_notify: false
  balance: 5.0
  pushplus_token: "xxxx,xxxx"
schema:
  phone: str
  password: password
  ignore_user_id: str
  enable_database_storage: bool
  db_name: str
  hass_url: url
  hass_token: str
  job_start_time: str
  retry_wait_time_offset_unit: int(2,30)
  log_level: str
  data_retention_days: int
  recharge_notify: bool 
  balance: float 
  pushplus_token: str
