name: "SGCC Electricity New"
version: "latest"
slug: "sgcc_electricity_new"
description: "获取国网电费数据的插件(新版)"
url: "https://github.com/ARC-MX/sgcc_electricity_new"
arch:
  - aarch64
  - amd64
host_network: true
startup: application
boot: auto
init: false
#image: "{arch}-sgcc_electricity_new"
map:
  - config:rw
options:
  phone: ""
  password: ""
  enable_database_storage: false
  db_name: "homeassistant.db"
  hass_url: "http://homeassistant.local:8123/"
  hass_token: ""
  job_start_time: "07:00"
  driver_implicitly_wait_time: 60
  retry_times_limit: 5
  login_expected_time: 60
  retry_wait_time_offset_unit: 10
  log_level: "INFO"
  data_retention_days: 7
  recharge_notify: false
  balance: 5.0
  pushplus_token: ""
schema:
  phone: str
  password: password
  IGNORE_USER_ID: "str?"
  enable_database_storage: bool
  db_name: str
  hass_url: str
  hass_token: str
  job_start_time: str
  driver_implicitly_wait_time: int
  retry_times_limit: int
  login_expected_time: int
  retry_wait_time_offset_unit: int
  log_level: str
  data_retention_days: int
  recharge_notify: bool 
  balance: float 
  pushplus_token: "str?"
