name: Docker Image CI armv7

on:
  push:
    paths:
      - 'scripts/**'
      - 'Dockerfile-for-github-action-armv7'
      - 'example.env'
      - 'requirements-armv7.txt'
      - '.github/workflows/docker-image-armv7.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Log into registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
    - name: Build and push Docker image
      run: |
        PLATFORMS=linux/arm/v7
        DOCKER_IMAGE=renhai/sgcc_electricity
        docker buildx build --platform $PLATFORMS -t $DOCKER_IMAGE:armv7-latest -t $DOCKER_IMAGE:armv7-1.3.3 --file Dockerfile-for-github-action-armv7 --push .