name: Docker Image Build

on:  
  workflow_dispatch:
    inputs:
      version:
        description: 'version of this branch'
        required: true
        type: string
    paths:
      - 'scripts/**'
      - 'Dockerfile-for-github-action'
      - 'requirements.txt'
      - 'example.env'
      - '.github/workflows/docker-image.yml'

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        PLATFORMS=linux/arm64,linux/amd64
        DOCKER_IMAGE=arcw/sgcc_electricity
        ARCH_TAGS="arm64 amd64"        
        VERSION=${{ inputs.version }}
        docker buildx build --build-arg VERSION=${VERSION} --platform $PLATFORMS -t $DOCKER_IMAGE:latest -t $DOCKER_IMAGE:${VERSION} --file Dockerfile-for-github-action .
